import './style.css';
import profileData from '../../../packages/physics/profiles/racer5.json' with { type: 'json' };
import { PHYSICS_VERSION, DT, clamp, cloneState, hoverThrottle, initialState, rate, step } from '../../../packages/physics/src/index';
import type { Input } from '../../../packages/physics/src/index';
import { FixedClock } from '../../../packages/physics/src/clock';
import { collision } from '../../../packages/physics/src/track';
import { Race } from '../../../packages/physics/src/race';
import { assistedInput } from '../../../packages/physics/src/assist';
import { createWorld } from './world';
import { Diagnostics } from './diagnostics';
import { ControllerPanel } from './controller-panel';
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T; const canvas=el<HTMLCanvasElement>('scene'); const profile=structuredClone(profileData); let state=initialState(profile),previous=cloneState(state); const clock=new FixedClock(),race=new Race(),keys=new Set<string>(); let paused=false,source='keyboard',cameraMode='chase',tilt=15,fov=75,flightMode='assisted',readyFrames=0,throttle=hoverThrottle(profile),hoverReference=true; let input:Input={throttle,roll:0,pitch:0,yaw:0}; let world:ReturnType<typeof createWorld>; let lastTime=0,lastUI=0,lastGraphTick=-1,resetPending='',resets=0,frameId=0; const diagnostics=new Diagnostics(el('rate-graph'),el('thrust-graph'),el('minimap'));
function message(text:string){el('flight-message').textContent=text;} function pause(reason:string){paused=true;keys.clear();clock.reset();if(race.startTick!==null)race.invalidate();el('pause').innerHTML='재개 <kbd>P</kbd>';message(reason);} const controller=new ControllerPanel(pause);
function reset(reason='시작 위치로 초기화 · 랩을 새로 시작합니다.'){state=initialState(profile);previous=cloneState(state);clock.reset();race.reset();diagnostics.reset();throttle=hoverThrottle(profile);hoverReference=true;lastGraphTick=-1;keys.clear();world?.resetCamera();resets++;message(reason);if(source==='gamepad')pause(reason+' · 스틱 확인 후 재개하세요.');}
function togglePause(){if(!paused){pause('일시정지 · 진행 중이던 랩은 무효입니다. R로 새 랩을 시작하세요.');return;}if(source==='gamepad'&&!controller.poll()){message('조종기 연결 또는 축 매핑을 먼저 확인하세요.');return;}if(el<HTMLDetailsElement>('input-settings').open){message('조종기 설정을 접은 뒤 재개하세요.');return;}paused=false;clock.reset();lastTime=performance.now();el('pause').innerHTML='일시정지 <kbd>P</kbd>';message(race.valid?'비행 재개 · 노란 게이트를 순서대로 통과하세요.':'연습 재개 · 현재 랩 무효, R로 새 랩 시작');}
function switchCamera(){cameraMode=cameraMode==='chase'?'fpv':'chase';el('camera').innerHTML=(cameraMode==='fpv'?'3인칭으로 전환':'FPV로 전환')+' <kbd>C</kbd>';el('camera').dataset.mode=cameraMode;world?.resetCamera();}
el('reset').onclick=()=>reset();el('pause').onclick=togglePause;el('camera').onclick=switchCamera;el<HTMLSelectElement>('flight-mode').onchange=e=>{flightMode=(e.target as HTMLSelectElement).value;el('mode-badge').textContent=flightMode==='assisted'?'쉬운 조종':'ACRO';race.bestSeconds=null;race.laps=0;reset('조종 모드 변경 · 서로 다른 모드의 기록은 비교하지 않습니다.');};el('hover').onclick=()=>{if(source==='keyboard'){hoverReference=true;throttle=hoverThrottle(profile,state.charge);}};el<HTMLSelectElement>('input-source').onchange=e=>{source=(e.target as HTMLSelectElement).value;reset('입력 방식 변경 · 새 주행 준비');if(source==='gamepad')pause('조종기 매핑과 스로틀을 확인한 뒤 재개하세요.');el<HTMLButtonElement>('hover').disabled=source!=='keyboard';};
el('panel-toggle').onclick=()=>{const panel=el('controls');panel.hidden=!panel.hidden;el('panel-toggle').textContent=panel.hidden?'설정 열기':'설정 접기';el('panel-toggle').setAttribute('aria-expanded',String(!panel.hidden));};if(innerWidth<=720)el('panel-toggle').click();
const tune=(id:string,callback:(value:number)=>void,format:(value:number)=>string,physics=false)=>{const field=el<HTMLInputElement>(id);field.oninput=()=>{const value=Number(field.value);if(!Number.isFinite(value))return;callback(value);el(id+'-out').textContent=format(value);if(physics){race.invalidate();message('튜닝 즉시 적용 · 현재 랩 무효, R로 새 랩을 시작하세요.');}};};const fixed=(v:number)=>v.toFixed(2);for(const[id,key]of[['rc-rate','rcRate'],['super-rate','superRate'],['expo','expo']] as const)tune(id,v=>{profile.rates[key]=v;el('max-rate').textContent='최대 '+Math.round(rate(1,profile.rates)*180/Math.PI)+' °/s · 세 축 공통';},fixed,true);tune('tilt',v=>tilt=v,v=>v+'°');tune('fov',v=>fov=v,v=>v+'°');tune('mass',v=>profile.massKg=v,v=>v.toFixed(2)+' kg',true);tune('thrust',v=>profile.maxMotorThrustN=v,v=>v.toFixed(1)+' N',true);tune('motor-lag',v=>profile.motorTimeConstantS=v/1000,v=>v+' ms',true);
function onKeyDown(event:KeyboardEvent){if((event.target as HTMLElement).closest('input,select,textarea,summary'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyS','KeyA','KeyD','KeyR','KeyP','KeyC','KeyH'].includes(event.code))event.preventDefault();if(!event.repeat){if(event.code==='KeyR')reset();if(event.code==='KeyP')togglePause();if(event.code==='KeyC')switchCamera();if(event.code==='KeyH')el('hover').click();}keys.add(event.code);} function onKeyUp(e:KeyboardEvent){keys.delete(e.code);} window.addEventListener('keydown',onKeyDown);window.addEventListener('keyup',onKeyUp);window.addEventListener('blur',()=>{keys.clear();if(!paused)pause('창 포커스를 잃어 비행을 멈췄습니다.');});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('탭이 숨겨져 비행을 멈췄습니다.');});const axis=(p:string,n:string)=>(keys.has(p)?1:0)-(keys.has(n)?1:0);const time=(seconds:number)=>{const ms=Math.floor(seconds*1000);return String(Math.floor(ms/60000)).padStart(2,'0')+':'+String(Math.floor(ms/1000)%60).padStart(2,'0')+'.'+String(ms%1000).padStart(3,'0');};
function updateUI(){el('altitude').innerHTML=state.position[1].toFixed(2)+' <em>m</em>';el('speed').innerHTML=Math.hypot(...state.velocity).toFixed(1)+' <em>m/s</em>';el('throttle-value').innerHTML=Math.round(input.throttle*100)+' <em>%</em>';el('battery').innerHTML=state.voltage.toFixed(1)+' <em>V</em>';el('lap-time').textContent=time(race.elapsed(state.tick));el('gate-progress').textContent='다음 게이트 '+(race.nextGate+1)+' / 5'+(race.valid?'':' · 랩 무효');el('best-lap').textContent=race.bestSeconds===null?'완료한 랩 없음':'최고 '+time(race.bestSeconds)+' · '+race.laps+'랩';const graphAxis=Number(el<HTMLSelectElement>('graph-axis').value);el('live-rate').textContent=(state.omega[graphAxis]!*180/Math.PI).toFixed(0)+' °/s';el('live-thrust').textContent=state.thrustN.toFixed(1)+' N';diagnostics.draw(graphAxis,state,race.nextGate);controller.updateDisplay();}
function frame(now:number){frameId=requestAnimationFrame(frame);const elapsed=lastTime?Math.max(0,(now-lastTime)/1000):0;lastTime=now;const padInput=controller.poll();if(readyFrames<3){readyFrames++;world.render(previous,state,1,cameraMode,tilt,fov,race.nextGate,0);if(readyFrames===3)el('status').textContent='3D 장면 준비 완료';updateUI();return;}if(!paused&&elapsed>.25)pause('긴 프레임 지연으로 중단');if(!paused&&source==='gamepad'&&!padInput)pause('조종기 연결 또는 매핑 오류');if(!paused){clock.advance(elapsed,()=>{if(resetPending)return;previous=cloneState(state);if(source==='keyboard'){if(keys.has('KeyW')||keys.has('KeyS'))hoverReference=false;if(hoverReference)throttle=hoverThrottle(profile,state.charge);else throttle=clamp(throttle+axis('KeyW','KeyS')*DT*.3,0,1);input={throttle,roll:axis('ArrowLeft','ArrowRight')*.35,pitch:axis('ArrowDown','ArrowUp')*.25,yaw:axis('KeyA','KeyD')*.35};}else input=padInput!;if(flightMode==='assisted'){const command=source==='keyboard'?{throttle:.5+axis('KeyW','KeyS')*.5,roll:axis('ArrowLeft','ArrowRight'),pitch:axis('ArrowDown','ArrowUp'),yaw:axis('KeyA','KeyD')}:input;input=assistedInput(state,command,profile);}step(state,input,profile);if(collision(previous.position,state.position)){resetPending='충돌 또는 훈련장 이탈';return;}const active=Math.abs(input.throttle-hoverThrottle(profile,state.charge))>.02||Math.abs(input.roll)+Math.abs(input.pitch)+Math.abs(input.yaw)>.01;if(race.update(previous.position,state.position,state.tick,active))message('랩 완료! '+time(race.lastSeconds!));if(state.tick%8===0&&state.tick!==lastGraphTick){diagnostics.sample(state,input,4*profile.maxMotorThrustN);lastGraphTick=state.tick;}});if(resetPending){const reason=resetPending;resetPending='';reset(reason);}}world.render(previous,state,paused?1:clock.alpha,cameraMode,tilt,fov,race.nextGate,Math.min(elapsed,.05));if(now-lastUI>70){updateUI();lastUI=now;}}
try{world=createWorld(canvas);el('version').textContent='PHYSICS '+PHYSICS_VERSION;world.render(previous,state,1,cameraMode,tilt,fov,0,0);updateUI();frameId=requestAnimationFrame(frame);}catch(error){el('status').textContent='3D 장면 초기화 실패';console.error(error);}import.meta.hot?.dispose(()=>{cancelAnimationFrame(frameId);world?.dispose();});
